Put filenames in ariadne diagnostics (#2927)
Changes ariadne diagnostics rendering to use file names in place of file
indices:

```

Error: Expected '=>' after pattern, found ':'
-   ╭─[ 0:18:19 ]
+   ╭─[ syntax_errors.baml:18:19 ]
    │
 18 │         a: int | b: bool => "bad"
    │                   ┬  
```

This is implemented in terms of `ariadne`'s `Cache` trait, which is
responsible for rendering span locations.

The ariadne cache is a mutable store of file contents indexed by their
filenames. It's a bit unfortunate that we have to pull in the whole
cache just to twiddle how spans are rendered. However maybe this speeds
up the way snippets of source are found when rendering the pretty
diagnostics? A consequence is that any driver of the compiler must first
initialize a mutable `DbSourceCache`, and pass it as a mutable ref to
the diagnostics rendering functions.